using System;

namespace BookingCareManagement.Domain.Aggregates.Invoice;

public class Invoice
{
    public Guid Id { get; private set; } = Guid.NewGuid();

    // Invoice number generated by database (identity, auto-increment)
    public int InvoiceNumber { get; private set; }

    // Link to appointment - one invoice per appointment
    public Guid AppointmentId { get; private set; }

    // Date the invoice was created
    public DateTime InvoiceDate { get; private set; } = DateTime.UtcNow;

    // Total amount for the invoice
    public decimal Total { get; private set; }

    // Simple status field - values like "Pending", "Paid"
    public string Status { get; private set; } = "Pending";

    private Invoice() { }

    public Invoice(Guid appointmentId, decimal total, DateTime? invoiceDate = null)
    {
        if (appointmentId == Guid.Empty) throw new ArgumentException("AppointmentId is required", nameof(appointmentId));

        AppointmentId = appointmentId;
        Total = total;
        InvoiceDate = invoiceDate ?? DateTime.UtcNow;
        Status = "Pending";
    }

    public void MarkPaid() => Status = "Paid";
    public void SetStatus(string status)
    {
        if (string.IsNullOrWhiteSpace(status)) throw new ArgumentException("Status is required", nameof(status));
        Status = status.Trim();
    }

    public void UpdateTotal(decimal total)
    {
        if (total < 0) throw new ArgumentOutOfRangeException(nameof(total), "Total must be >= 0");
        Total = total;
    }
}
