using BookingCareManagement.Domain.Abstractions;
using Microsoft.AspNetCore.Mvc;
using QuestPDF.Fluent;
using QuestPDF.Infrastructure;
using QuestPDF.Helpers;
using System.Globalization;
using Microsoft.Extensions.Logging;

namespace BookingCareManagement.Web.Areas.Doctor.Controllers;

[ApiController]
[Route("api/[controller]")]
public class InvoiceController : ControllerBase
{
    private readonly IInvoiceRepository _invoiceRepository;
    private readonly ILogger<InvoiceController> _logger;

    public InvoiceController(IInvoiceRepository invoiceRepository, ILogger<InvoiceController> logger)
    {
        _invoiceRepository = invoiceRepository;
        _logger = logger;
    }

    // GET api/invoice
    [HttpGet]
    public async Task<IActionResult> GetAll(CancellationToken cancellationToken)
    {
        var items = await _invoiceRepository.GetAllWithDetailsAsync(cancellationToken);
        return Ok(items);
    }

    // POST api/invoice/{id}/mark-as-paid
    [HttpPost("{id:guid}/mark-as-paid")]
    public async Task<IActionResult> MarkAsPaid([FromRoute] Guid id, CancellationToken cancellationToken)
    {
        var ok = await _invoiceRepository.MarkAsPaidAsync(id, cancellationToken);
        if (!ok) return NotFound(new ProblemDetails { Title = "Not Found", Detail = "Invoice not found" });
        return NoContent();
    }

    // GET api/invoice/{id}/pdf
    [HttpGet("{id:guid}/pdf")]
    public async Task<IActionResult> GetPdf([FromRoute] Guid id, CancellationToken cancellationToken)
    {
        var items = await _invoiceRepository.GetAllWithDetailsAsync(cancellationToken);
        var inv = items.FirstOrDefault(i => i.Id == id);
        if (inv == null) return NotFound(new ProblemDetails { Title = "Not Found", Detail = "Invoice not found" });

        // Build PDF using QuestPDF
        var doc = new InvoicePdfDocument(inv);

        using var ms = new MemoryStream();
        doc.GeneratePdf(ms);
        ms.Position = 0;

        var fileName = $"Invoice-{inv.InvoiceNumber}.pdf";
        return File(ms.ToArray(), "application/pdf", fileName);
    }

    // Simple QuestPDF document
    private class InvoicePdfDocument : IDocument
    {
        private readonly BookingCareManagement.Application.Features.Invoices.Dtos.InvoiceListDto _inv;

        public InvoicePdfDocument(BookingCareManagement.Application.Features.Invoices.Dtos.InvoiceListDto inv)
        {
            _inv = inv;
        }

        public DocumentMetadata GetMetadata() => DocumentMetadata.Default;

        public void Compose(IDocumentContainer container)
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(30);
                page.PageColor(Colors.White);
                page.DefaultTextStyle(x => x.FontSize(12));

                page.Header().Row(row =>
                {
                    row.RelativeColumn().Column(col =>
                    {
                        col.Item().Text("Your Clinic").Bold().FontSize(18);
                        col.Item().Text("Address line 1");
                        col.Item().Text("Phone: +84 123 456 789");
                    });

                    row.ConstantColumn(150).AlignRight().Column(col =>
                    {
                        col.Item().Text($"Invoice #{_inv.InvoiceNumber}").Bold();
                        col.Item().Text(_inv.InvoiceDate.ToString("yyyy-MM-dd"));
                    });
                });

                page.Content().PaddingTop(10).Column(col =>
                {
                    col.Item().Row(r =>
                    {
                        r.RelativeColumn().Column(c =>
                        {
                            c.Item().Text("Bill To:").SemiBold();
                            c.Item().Text(_inv.CustomerName);
                            if (!string.IsNullOrWhiteSpace(_inv.CustomerEmail)) c.Item().Text(_inv.CustomerEmail);
                        });

                        r.RelativeColumn().AlignRight().Column(c =>
                        {
                            c.Item().Text("Status:").SemiBold();
                            c.Item().Text(_inv.Status ?? string.Empty);
                        });
                    });

                    col.Item().PaddingTop(10).Element(ComposeTable);

                    col.Item().PaddingTop(10).AlignRight().Column(c =>
                    {
                        c.Item().Text($"Total: {_inv.Total}").Bold();
                    });
                });

                page.Footer().AlignCenter().Text("Generated by BookingCareManagement");
            });
        }

        void ComposeTable(IContainer container)
        {
            container.Table(table =>
            {
                table.ColumnsDefinition(columns =>
                {
                    columns.RelativeColumn();
                    columns.ConstantColumn(60);
                    columns.ConstantColumn(100);
                });

                table.Header(header =>
                {
                    header.Cell().Text("Service").Bold();
                    header.Cell().AlignCenter().Text("Qty").Bold();
                    header.Cell().AlignRight().Text("Amount").Bold();
                });

                table.Cell().Text(string.IsNullOrWhiteSpace(_inv.ServiceName) ? "Service" : _inv.ServiceName);
                table.Cell().AlignCenter().Text(_inv.ServiceQty.ToString());
                table.Cell().AlignRight().Text(_inv.Total.ToString());
            });
        }
    }
}
